name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build Go program
      working-directory: ./Resty
      run: go build -o TestResty.exe .

    - name: Build Docker image
      working-directory: ./Resty
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: loadtestresty:latest
        build-args: |
          ARG_REQUESTS=10 
      
    - name: Log in to Docker registry
      uses: docker/login-action@v1
      with:
        registry: apimloadtest.azurecr.io
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}

    - name: Push Docker image to registry
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: apimloadtest.azurecr.io/loadtestresty:latest:latest