ARG ARG_EVENHUB=""
ARG ARG_REQUESTS=10
ARG ARG_URL=https://httpbin.org/get

# ENV EVENTHUB_CONNECTION_STRING=event_hub_connection_here
# ENV REQUESTS=10
# ENV URL=https://httpbin.org/get

ENV EVENTHUB_CONNECTION_STRING=ARG_EVENHUB
ENV REQUESTS=ARG_REQUESTS
ENV URL=ARG_URL

# Use the official Golang image as the base image
FROM golang:1.16-alpine AS build

# Set the working directory to /app
WORKDIR /app

# Copy the source code to the container
COPY . .

# Build the Golang program
RUN go build -o TestResty.exe .

# Use a minimal Alpine image as the base image for the final image
FROM alpine:3.14

# Copy the built binary from the previous stage
COPY --from=build /app/TestResty.exe /app/TestResty.exe

# Set the working directory to /app
WORKDIR /app

# Install any necessary dependencies
RUN apk add --no-cache ca-certificates

# Expose the port that the program listens on
EXPOSE 8080

# Start the program when the container starts
CMD ["./TestResty.exe -r $REQUESTS -url $URL -eventHub $EVENTHUB_CONNECTION_STRING"]